<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */


$productCollection = $block->getProductCollection();
if ($productCollection) {
    $productCollection->setPageSize(10); // Giới hạn số lượng sản phẩm
}

if ($exist = ($productCollection && $productCollection->getSize())) {
    $type = 'widget-new-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $title = __('New Products');
    $items = $productCollection->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
?>

<?php if ($exist): ?>
    <?php
    $bizkickHelper = $this->helper('Hiddentechies\Bizkick\Helper\Data');
    $showNewLabel = $bizkickHelper->getConfigValue('bizkicksettings/category_settings/show_new_label');
    $showSaleLabel = $bizkickHelper->getConfigValue('bizkicksettings/category_settings/show_sale_label');
    $showBorder = $bizkickHelper->getConfigValue('bizkicksettings/category_settings/show_border');
    ?>
    <div style="margin-bottom: 0;" class="owl-button-top above-padding below-padding block widget block-new-products <?php echo $this->escapeHtml($mode); ?>">
        <div class="page-title-main">
            <strong role="heading" aria-level="2"><?php echo $this->escapeHtml($title); ?></strong>
        </div>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php echo $this->escapeHtml($mode); ?> <?php echo $this->escapeHtml($mode); ?>">
                <div class="slider-outer">
                    <ol class="product-widget-slider products list items product-items <?php echo $this->escapeHtml($type); ?>">
                        <?php foreach ($items as $_item): ?>
                            <li class="product-item product-slider">
                                <div class="product-item-info">
                                    <div class="product-img-main">
                                        <a href="<?php echo $block->getProductUrl($_item); ?>" class="product-item-photo <?php if ($showBorder == 1) { echo 'add-border'; } ?>">
                                            <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                            <?php
                                            if ($showNewLabel == 1) {
                                                $fromDate = $_item->getNewsFromDate();
                                                $toDate = $_item->getNewsToDate();

                                                if ($fromDate && $toDate) {
                                                    $fromDate = strtotime($fromDate);
                                                    $toDate = strtotime($toDate);
                                                    $now = time();

                                                    if ($fromDate <= $now && $now <= $toDate) {
                                                        ?>
                                                        <span class="new-label"><?php echo __('New'); ?></span>
                                                        <?php
                                                    }
                                                }
                                            }

                                            if ($showSaleLabel == 1) {
                                                $special_price = $_item->getSpecialPrice();
                                                $regular_price = $_item->getPrice();
                                                if ($special_price && $special_price > 0 && $special_price < $regular_price) {
                                                    $fromSpecialDate = $_item->getSpecialFromDate();
                                                    $toSpecialDate = $_item->getSpecialToDate();

                                                    if ($fromSpecialDate && $toSpecialDate) {
                                                        $fromSpecialDate = strtotime($fromSpecialDate);
                                                        $toSpecialDate = strtotime($toSpecialDate);
                                                        $now = time();

                                                        if ($fromSpecialDate <= $now && $now <= $toSpecialDate) {
                                                            ?>
                                                            <span class="sale-label"><?php echo __('Sale'); ?></span>
                                                            <?php
                                                        }
                                                    }
                                                }
                                            }
                                            ?>
                                        </a>
                                        <div class="product-item-inner">
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="product actions product-item-actions">
                                                    <div class="actions-secondary" data-role="add-to-links">
                                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                            <a href="#"
                                                               data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
                                                               class="action towishlist" data-action="add-to-wishlist"
                                                               title="<?php echo __('Add to Wish List'); ?>">
                                                                <span><?php echo __('Add to Wish List'); ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                            <a href="#" class="action tocompare"
                                                               data-post='<?php echo $compareHelper->getPostDataParams($_item); ?>'
                                                               title="<?php echo __('Add to Compare'); ?>">
                                                                <span><?php echo __('Add to Compare'); ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?php echo $block->escapeHtml($_item->getName()); ?>"
                                               href="<?php echo $block->getProductUrl($_item); ?>"
                                               class="product-item-link">
                                                   <?php echo $block->escapeHtml($_item->getName()); ?>
                                            </a>
                                        </strong>
                                        <?php
                                        echo $block->getProductPriceHtml($_item, $type);
                                        ?>

                                        <?php if ($templateType): ?>
                                            <?php echo $block->getReviewsSummaryHtml($_item, $templateType); ?>
                                        <?php endif; ?>

                                        <?php if ($showCart): ?>
                                            <div class="product-item-inner">
                                                <div class="product-item-actions">
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                <button class="action tocart primary"
                                                                        data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item); ?>"}}'
                                                                        type="button" title="<?php echo __('Add to Cart'); ?>">
                                                                    <span><?php echo __('Add to Cart'); ?></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php
                                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
                                                                ?>
                                                                <button class="action tocart primary"
                                                                        data-post='<?php echo $postData; ?>'
                                                                        type="button" title="<?php echo __('Add to Cart'); ?>">
                                                                    <span><?php echo __('Add to Cart'); ?></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php else: ?>
                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <div class="stock available">
                                                                    <span><?php echo __('In stock'); ?></span>
                                                                </div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable">
                                                                    <span><?php echo __('Out of stock'); ?></span>
                                                                </div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ol>
                </div>
            </div>
            <?php echo $block->getPagerHtml(); ?>
        </div>
    </div>
    <script type="text/javascript">
        require(['jquery', 'bizkickowlcarousel'], function($) {
            $(document).ready(function() {
                $(".product-widget-slider").owlCarousel({
                    items: 5,
                    itemsDesktop: [1199, 8], 
                    itemsDesktopSmall: [991, 6],
                    itemsTablet: [767, 4],
                    itemsTabletSmall: [639, 3],
                    itemsMobile: [479, 2],
                    pagination: false,
                    navigationText: [
                        "<div class='left-arrow'><i class='fa fa-angle-left'></i></div>",
                        "<div class='right-arrow'><i class='fa fa-angle-right'></i></div>" 
                    ],
                    navigation: true,
                });
            });
            $(window).on('load', function() {
                $('.product-widget-slider .product-slider').show();
            });
        });
    </script>
<?php endif; ?>
