<?php
declare(strict_types=1);

use Magento\Framework\App\Bootstrap;
use Magento\Framework\App\State;
use Magento\Framework\Mail\Address;
use Magento\Framework\Mail\EmailMessageInterface;
use Magento\Framework\Mail\MimeInterface;
use Magento\Framework\Mail\MimeMessageInterface;
use Magento\Framework\Mail\MimePartInterface;
use Magento\Framework\Mail\TransportInterface;

require __DIR__ . '/../app/bootstrap.php';

$recipientEmail = $argv[1] ?? '22024552@vnu.edu.vn';
$marker = $argv[2] ?? date('YmdHis');

$bootstrap = Bootstrap::create(BP, $_SERVER);
$objectManager = $bootstrap->getObjectManager();

try {
    $objectManager->get(State::class)->setAreaCode('frontend');
} catch (\Exception $e) {
    // Area code may already be set when this script is reused in the same process.
}

$types = [
    'Contact form notification' => 'Mô phỏng email liên hệ từ khách hàng gửi tới DAL Active.',
    'Customer account welcome' => 'Mô phỏng email chào mừng sau khi khách đăng ký tài khoản.',
    'Customer password reset' => 'Mô phỏng email đặt lại mật khẩu cho tài khoản khách hàng.',
    'Newsletter subscription' => 'Mô phỏng email xác nhận đăng ký nhận bản tin.',
    'Sales order confirmation' => 'Mô phỏng email xác nhận đơn hàng mới.',
    'Sales invoice' => 'Mô phỏng email hóa đơn đơn hàng.',
    'Sales shipment' => 'Mô phỏng email thông báo giao hàng.',
    'Sales credit memo' => 'Mô phỏng email hoàn tiền/credit memo.',
    'Product stock alert' => 'Mô phỏng email báo sản phẩm đã có hàng.',
];

$from = [
    $objectManager->create(Address::class, [
        'email' => 'dalactive99@gmail.com',
        'name' => 'DAL Active Sports',
    ]),
];

$to = [
    $objectManager->create(Address::class, [
        'email' => $recipientEmail,
        'name' => 'DAL Active Test Recipient',
    ]),
];

$sent = [];
$failed = [];

foreach ($types as $type => $description) {
    $subject = sprintf('[DAL Email Test %s] %s', $marker, $type);
    $html = sprintf(
        '<h2>%s</h2><p>%s</p><p>Recipient: %s</p><p>Marker: %s</p><p>Generated by Magento mail transport.</p>',
        htmlspecialchars($type, ENT_QUOTES, 'UTF-8'),
        htmlspecialchars($description, ENT_QUOTES, 'UTF-8'),
        htmlspecialchars($recipientEmail, ENT_QUOTES, 'UTF-8'),
        htmlspecialchars($marker, ENT_QUOTES, 'UTF-8')
    );

    try {
        $part = $objectManager->create(MimePartInterface::class, [
            'content' => $html,
            'type' => MimeInterface::TYPE_HTML,
            'charset' => 'utf-8',
            'encoding' => MimeInterface::ENCODING_QUOTED_PRINTABLE,
        ]);

        $body = $objectManager->create(MimeMessageInterface::class, [
            'parts' => [$part],
        ]);

        $message = $objectManager->create(EmailMessageInterface::class, [
            'body' => $body,
            'to' => $to,
            'from' => $from,
            'subject' => $subject,
            'encoding' => 'utf-8',
        ]);

        $transport = $objectManager->create(TransportInterface::class, [
            'message' => $message,
        ]);
        $transport->sendMessage();
        $sent[] = $subject;
    } catch (\Throwable $e) {
        $failed[] = $subject . ' :: ' . $e->getMessage();
    }
}

echo "recipient={$recipientEmail}\n";
echo "marker={$marker}\n";
echo "sent=" . count($sent) . "\n";
foreach ($sent as $subject) {
    echo "OK {$subject}\n";
}

if ($failed) {
    echo "failed=" . count($failed) . "\n";
    foreach ($failed as $error) {
        echo "FAIL {$error}\n";
    }
    exit(1);
}
