<?php
/**
 * @var \Dalactive\Weather\Block\Weather $block
 */
?>

<?php
// Define the list of cities you want to display
$cities = ['HaNoi', 'London', 'New York', 'Tokyo', 'Sydney', 'Paris', 'Berlin', 'Moscow', 'Beijing', 'Seoul', 'San Francisco', 'Ho Chi Minh City', 'Bangkok', 'Singapore', 'Kuala Lumpur', 'Jakarta', 'Manila'];
$weatherDataList = $block->getMultipleWeatherData($cities);
?>

<?php if (!empty($weatherDataList)): ?>
    <div class="weather-container">
        <?php foreach ($weatherDataList as $weatherData): ?>
            <div class="weather-card">
                <h2><?php echo $this->escapeHtml($weatherData['name']); ?>, <?php echo $this->escapeHtml($weatherData['sys']['country']); ?></h2>
                <p>Nhiệt độ: <?php echo $this->escapeHtml($weatherData['main']['temp']); ?> °C</p>
                <p>Thời tiết: <?php echo $this->escapeHtml(ucfirst($weatherData['weather'][0]['description'])); ?></p>
                <p>Độ ẩm: <?php echo $this->escapeHtml($weatherData['main']['humidity']); ?>%</p>
                <p>Tốc độ gió: <?php echo $this->escapeHtml($weatherData['wind']['speed']); ?> m/s</p>
            </div>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <p>Thời tiết đang cập nhật, xin hãy thử lại sau.</p>
<?php endif; ?>

